apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
      - key: "karpenter.k8s.aws/instance-family"
        operator: In
        values: ["c6i"]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      expireAfter: 720h # 30 * 24h = 720h
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2023
  role: "KarpenterNodeRole-sauravag-karpenter-demo"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "sauravag-karpenter-demo"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "sauravag-karpenter-demo"
  amiSelectorTerms: 
    - alias: al2023@latest

